CREATE SCHEMA ODS;

USE SCHEMA ODS;

-- Business table
DROP TABLE IF EXISTS BUSINESS;
CREATE TABLE BUSINESS (
    BUSINESS_ID STRING PRIMARY KEY, 
    NAME STRING, 
    ADDRESS STRING, 
    STATE STRING, 
    CITY STRING,
    POSTAL_CODE STRING,
    REVIEW_COUNT INT,
    STARS INT,
    IS_OPEN INT
);

-- Covid features
DROP TABLE IF EXISTS COVID_FEATURES;
CREATE TABLE COVID_FEATURES (
    BUSINESS_ID STRING PRIMARY KEY,
    CALL_TO_ACTION_ENABLED STRING,
    COVID_BANNER STRING,
    GRUBHUB_ENABLED STRING,
    REQUEST_QUOTE_ENABLED STRING,
    TEMPORARILY_CLOSED_UNTIL STRING,
    VIRTUAL_SERVICES_OFFERED STRING,
    DELIVERY_OR_TAKEOUT STRING,
    HIGHLIGHTS STRING,
    CONSTRAINT FKEY_BUSINESS_ID FOREIGN KEY (BUSINESS_ID) REFERENCES BUSINESS(BUSINESS_ID)
);

-- User table
DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
    USER_ID STRING PRIMARY KEY,
    NAME STRING NOT NULL,
    AVERAGE_STARS FLOAT,
    YELPING_SINCE TIMESTAMP,
    REVIEW_COUNT INT
);

-- Temperature table
DROP TABLE IF EXISTS TEMPERATURE
CREATE TABLE TEMPERATURE(
    DATE DATE PRIMARY KEY,
    MIN FLOAT,
    MAX FLOAT,
    NORMAL_MIN FLOAT,
    NORMAL_MAX FLOAT
);

-- Precipitation table
DROP TABLE IF EXISTS PRECIPITATION
CREATE TABLE PRECIPITATION (
    DATE DATE PRIMARY KEY,
    PRECIPITATION FLOAT,
    PRECIPITATION_NORMAL FLOAT
);

-- Checkin table
DROP TABLE IF EXISTS CHECKIN
CREATE TABLE CHECKIN (
    CHECKIN_ID INT IDENTITY,
    BUSINESS_ID STRING,
    DATE TIMESTAMP,
    CONSTRAINT FKEY_BUSINESS_ID FOREIGN KEY (BUSINESS_ID) REFERENCES BUSINESS(BUSINESS_ID)
);

-- Tip table
DROP TABLE IF EXISTS TIP
CREATE TABLE TIP (
    BUSINESS_ID STRING NOT NULL FOREIGN KEY REFERENCES BUSINESS(BUSINESS_ID),
    USER_ID STRING NOT NULL FOREIGN KEY REFERENCES USER(USER_ID),
    COMPLIMENT_COUNT INT,
    TIP_TXT STRING,
    DATE TIMESTAMP,
    CONSTRAINT PK_BUSINESS_ID_USER_ID PRIMARY KEY (BUSINESS_ID, USER_ID)
);

-- Review table
DROP TABLE IF EXISTS REVIEW
CREATE TABLE REVIEW (
    REVIEW_ID STRING PRIMARY KEY,
    BUSINESS_ID STRING NOT NULL FOREIGN KEY REFERENCES BUSINESS(BUSINESS_ID),
    USER_ID STRING NOT NULL FOREIGN KEY REFERENCES USER(USER_ID),
    DATE TIMESTAMP,
    STARS INT,
    COOL INT,
    FUNNY INT,
    USEFUL INT,
    REVIEW_TXT STRING
);

