SELECT
    db.NAME as BUSINESS,
    fr.DATE as DATE,
    AVG(fr.STARS) AS AVG_STAR_RATING,
    dt.MIN as TEMP_MIN,
    dt.NORMAL_MIN as TEMP_MIN_NORMAL,
    dt.MAX as TEMP_MAX,
    dt.NORMAL_MAX as TEMP_MAX_NORMAL,
    dp.PRECIPITATION as PRECIPITATION,
    dp.PRECIPITATION_NORMAL

FROM FACT_REVIEW fr
INNER JOIN DIM_BUSINESS db
ON fr.BUSINESS_ID = db.BUSINESS_ID
LEFT OUTER JOIN DIM_DATE dd
on fr.DATE = dd.DATE
LEFT OUTER JOIN DIM_TEMPERATURE dt
ON fr.DATE = dt.DATE
LEFT OUTER JOIN DIM_PRECIPITATION dp
on fr.DATE = dp.DATE
GROUP BY db.BUSINESS_ID, db.NAME, fr.DATE, dt.MIN, dt.NORMAL_MIN, dt.MAX, dt.NORMAL_MAX, dp.PRECIPITATION, dp.PRECIPITATION_NORMAL
ORDER BY AVG_STAR_RATING;