-- Populate dim business table
INSERT INTO DIM_BUSINESS
SELECT * FROM UDACITYPROJECT.ODS.BUSINESS;

-- Populate dim user table
INSERT INTO DIM_USER
SELECT * FROM UDACITYPROJECT.ODS.USER;

-- Populate dim temperature
INSERT INTO DIM_TEMPERATURE
SELECT * FROM UDACITYPROJECT.ODS.TEMPERATURE;

-- Populate dim precipitation
INSERT INTO DIM_PRECIPITATION
SELECT * FROM UDACITYPROJECT.ODS.PRECIPITATION;

-- Populate dim date
INSERT INTO DIM_DATE
SELECT 
    DISTINCT DATE, 
    DAY(DATE) AS DAY,
    WEEK(DATE) AS WEEK,
    MONTH(DATE) AS MONTH,
    QUARTER(DATE) AS QUARTER,
    YEAR(DATE) AS YEAR
FROM 
(
  SELECT DATE FROM UDACITYPROJECT.ODS.TEMPERATURE
  UNION
  SELECT DATE FROM UDACITYPROJECT.ODS.PRECIPITATION
  UNION
  SELECT DISTINCT DATE(DATE) FROM UDACITYPROJECT.ODS.REVIEW
);

-- Populate fact reviews
INSERT INTO FACT_REVIEW
SELECT 
    REVIEW_ID,
    BUSINESS_ID,
    USER_ID,
    DATE(DATE) AS DATE,
    STARS,
    COOL,
    FUNNY,
    USEFUL,
    REVIEW_TXT
FROM UDACITYPROJECT.ODS.REVIEW;